path: ./Dataset/For YOLO/Bee  

train: images/train
val: images/val

nc: 1 
names: ['bee']

# Image size
imgsz: 640  # Image size for training and inference

# Data augmentation
augment:
  # Augmentation parameters
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 0.0
  translate: 0.1
  scale: 0.5
  shear: 0.0
  perspective: 0.0
  flipud: 0.5
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.5

# Optimizer
optimizer: ADAM  # Optimizer
lr0: 0.01  # Initial learning rate
momentum: 0.937
weight_decay: 0.0005

# Scheduler
epochs: 300  # Number of epochs
warmup_epochs: 10
warmup_momentum: 0.8
warmup_bias_lr: 0.1
lrf: 0.1  # Final learning rate

# Training parameters
batch_size: 16
workers: 8
project: runs/train  # Output directory
name: bees  # Experiment name