path: E:\Mele-RIMBA\Datasets\For YOLO\Bee

train: images/train
val: images/val

nc: 1 
names: ['Insect']

imgsz: 640  

# Data augmentation
augment:
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 0.0
  translate: 0.1
  scale: 0.5
  shear: 0.0
  perspective: 0.0
  flipud: 0.5
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.5

batch_size: 16
workers: 8
project: runs/train 
name: bees  
cache: True